/**
 * Production server entrypoint.
 *
 * Usage:
 *   deno task build          # compile routes + islands with Vite
 *   deno task start:prod     # serve on WEB_PORT (default 8081)
 *
 * This file is also the deno compile target for zephyr-x9s:
 *   deno compile -A --output zephyr-web server.ts
 *
 * Unlike main.ts (used by Vite / deno serve), this file owns the HTTP server
 * via Deno.serve so that WEB_PORT is respected at runtime rather than as a
 * CLI flag.  app.listen() in main.ts is intentionally NOT used here — see
 * https://github.com/denoland/fresh/issues/3548 for why it does not work with
 * file-based routing in Fresh v2.
 */
import '@std/dotenv/load';

// Generated by `deno task build`. Must exist before running this file.
// @ts-ignore — _fresh/server.js is produced at build time, not present in source
import app from './_fresh/server.js';

const port = parseInt(Deno.env.get('WEB_PORT') ?? '8081', 10);

console.log(`Zephyr Web → http://localhost:${port}/`);
Deno.serve({ port }, (req: Request) =>
  (app as { fetch(r: Request): Promise<Response> }).fetch(req),
);
